CREATE TABLE normative_documenti (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  titolo VARCHAR(255) NOT NULL,
  titolo_breve VARCHAR(120) NOT NULL,
  tipo_documento VARCHAR(60) NOT NULL,
  ente_emittente VARCHAR(160) NULL,
  numero_atto VARCHAR(80) NULL,
  data_documento DATE NULL,
  data_pubblicazione DATE NULL,
  data_decorrenza DATE NULL,
  data_scadenza DATE NULL,
  stato_vigenza VARCHAR(40) NOT NULL DEFAULT 'da_verificare',
  versione VARCHAR(60) NOT NULL DEFAULT '1',
  descrizione TEXT NULL,
  file_originale VARCHAR(255) NULL,
  nome_file_originale VARCHAR(255) NULL,
  mime_type VARCHAR(120) NULL,
  dimensione_file BIGINT UNSIGNED NULL,
  hash_sha256 CHAR(64) NULL,
  fonte_url VARCHAR(500) NULL,
  stato_importazione VARCHAR(40) NOT NULL DEFAULT 'completata',
  needs_review TINYINT(1) NOT NULL DEFAULT 0,
  created_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FULLTEXT normative_documenti_fulltext (titolo, titolo_breve, descrizione),
  INDEX normative_documenti_tipo_idx (tipo_documento),
  INDEX normative_documenti_vigenza_idx (stato_vigenza),
  CONSTRAINT normative_documenti_created_by_fk FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE normative_nodi (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  documento_id BIGINT UNSIGNED NOT NULL,
  parent_id BIGINT UNSIGNED NULL,
  tipo_nodo VARCHAR(40) NOT NULL,
  codice VARCHAR(40) NULL,
  titolo VARCHAR(255) NOT NULL,
  ordinamento INT UNSIGNED NOT NULL DEFAULT 0,
  livello TINYINT UNSIGNED NOT NULL DEFAULT 0,
  pagina_inizio INT UNSIGNED NULL,
  pagina_fine INT UNSIGNED NULL,
  testo_introduttivo TEXT NULL,
  note TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX normative_nodi_documento_idx (documento_id),
  INDEX normative_nodi_parent_idx (parent_id),
  INDEX normative_nodi_tipo_idx (tipo_nodo),
  CONSTRAINT normative_nodi_documento_fk FOREIGN KEY (documento_id) REFERENCES normative_documenti(id) ON DELETE CASCADE,
  CONSTRAINT normative_nodi_parent_fk FOREIGN KEY (parent_id) REFERENCES normative_nodi(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE normative_articoli (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  documento_base_id BIGINT UNSIGNED NOT NULL,
  nodo_id BIGINT UNSIGNED NULL,
  numero VARCHAR(40) NULL,
  numero_normalizzato VARCHAR(40) NULL,
  rubrica VARCHAR(255) NOT NULL,
  slug VARCHAR(255) NOT NULL,
  ordinamento INT UNSIGNED NOT NULL DEFAULT 0,
  articolo_logico_key VARCHAR(255) NOT NULL,
  stato VARCHAR(40) NOT NULL DEFAULT 'vigente',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY normative_articoli_key_unique (articolo_logico_key),
  INDEX normative_articoli_documento_idx (documento_base_id),
  INDEX normative_articoli_nodo_idx (nodo_id),
  INDEX normative_articoli_numero_idx (numero_normalizzato),
  FULLTEXT normative_articoli_fulltext (rubrica),
  CONSTRAINT normative_articoli_documento_fk FOREIGN KEY (documento_base_id) REFERENCES normative_documenti(id) ON DELETE CASCADE,
  CONSTRAINT normative_articoli_nodo_fk FOREIGN KEY (nodo_id) REFERENCES normative_nodi(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE normative_articoli_versioni (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  articolo_id BIGINT UNSIGNED NOT NULL,
  documento_fonte_id BIGINT UNSIGNED NOT NULL,
  versione VARCHAR(60) NOT NULL DEFAULT '1',
  testo_integrale MEDIUMTEXT NOT NULL,
  testo_normalizzato MEDIUMTEXT NOT NULL,
  data_inizio_vigenza DATE NULL,
  data_fine_vigenza DATE NULL,
  stato_vigenza VARCHAR(40) NOT NULL DEFAULT 'da_verificare',
  tipo_modifica VARCHAR(40) NOT NULL DEFAULT 'consolidamento',
  fonte_modifica_testuale VARCHAR(255) NULL,
  pagina_inizio INT UNSIGNED NULL,
  pagina_fine INT UNSIGNED NULL,
  hash_testo CHAR(64) NOT NULL,
  needs_review TINYINT(1) NOT NULL DEFAULT 1,
  note_revisione TEXT NULL,
  created_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX normative_versioni_articolo_idx (articolo_id),
  INDEX normative_versioni_fonte_idx (documento_fonte_id),
  INDEX normative_versioni_vigenza_idx (stato_vigenza, data_inizio_vigenza, data_fine_vigenza),
  FULLTEXT normative_versioni_fulltext (testo_normalizzato),
  CONSTRAINT normative_versioni_articolo_fk FOREIGN KEY (articolo_id) REFERENCES normative_articoli(id) ON DELETE CASCADE,
  CONSTRAINT normative_versioni_fonte_fk FOREIGN KEY (documento_fonte_id) REFERENCES normative_documenti(id) ON DELETE CASCADE,
  CONSTRAINT normative_versioni_created_by_fk FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE normative_unita_testuali (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  versione_articolo_id BIGINT UNSIGNED NOT NULL,
  parent_id BIGINT UNSIGNED NULL,
  tipo_unita VARCHAR(40) NOT NULL DEFAULT 'capoverso',
  numero VARCHAR(40) NULL,
  etichetta VARCHAR(120) NULL,
  testo MEDIUMTEXT NOT NULL,
  testo_normalizzato MEDIUMTEXT NOT NULL,
  ordinamento INT UNSIGNED NOT NULL DEFAULT 0,
  livello TINYINT UNSIGNED NOT NULL DEFAULT 0,
  pagina INT UNSIGNED NULL,
  anchor VARCHAR(120) NULL,
  hash_testo CHAR(64) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX normative_unita_versione_idx (versione_articolo_id),
  INDEX normative_unita_parent_idx (parent_id),
  INDEX normative_unita_tipo_idx (tipo_unita),
  FULLTEXT normative_unita_fulltext (testo_normalizzato),
  CONSTRAINT normative_unita_versione_fk FOREIGN KEY (versione_articolo_id) REFERENCES normative_articoli_versioni(id) ON DELETE CASCADE,
  CONSTRAINT normative_unita_parent_fk FOREIGN KEY (parent_id) REFERENCES normative_unita_testuali(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE normative_search_index (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  entity_type VARCHAR(40) NOT NULL,
  entity_id BIGINT UNSIGNED NOT NULL,
  documento_id BIGINT UNSIGNED NOT NULL,
  titolo VARCHAR(255) NOT NULL,
  contenuto MEDIUMTEXT NOT NULL,
  contenuto_normalizzato MEDIUMTEXT NOT NULL,
  metadati_json JSON NULL,
  stato_vigenza VARCHAR(40) NOT NULL DEFAULT 'da_verificare',
  data_inizio DATE NULL,
  data_fine DATE NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY normative_search_entity_unique (entity_type, entity_id),
  INDEX normative_search_documento_idx (documento_id),
  INDEX normative_search_vigenza_idx (stato_vigenza, data_inizio, data_fine),
  FULLTEXT normative_search_fulltext (titolo, contenuto_normalizzato),
  CONSTRAINT normative_search_documento_fk FOREIGN KEY (documento_id) REFERENCES normative_documenti(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE normative_importazioni (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  documento_id BIGINT UNSIGNED NOT NULL,
  stato VARCHAR(40) NOT NULL DEFAULT 'caricata',
  fase VARCHAR(60) NOT NULL DEFAULT 'migrazione',
  avanzamento_percentuale TINYINT UNSIGNED NOT NULL DEFAULT 0,
  elementi_totali INT UNSIGNED NOT NULL DEFAULT 0,
  elementi_elaborati INT UNSIGNED NOT NULL DEFAULT 0,
  messaggio VARCHAR(500) NULL,
  errore TEXT NULL,
  configurazione_json JSON NULL,
  risultato_json JSON NULL,
  iniziata_il DATETIME NULL,
  completata_il DATETIME NULL,
  created_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX normative_import_documento_idx (documento_id),
  INDEX normative_import_stato_idx (stato),
  CONSTRAINT normative_import_documento_fk FOREIGN KEY (documento_id) REFERENCES normative_documenti(id) ON DELETE CASCADE,
  CONSTRAINT normative_import_created_by_fk FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
